##MAINCLASS=org.mark.llamacpp.server.LlamaServer
-Djava.class.path=classes;lib\gson-2.8.9.jar;lib\netty-all-4.1.35.Final.jar;lib\log4j-api-2.22.1.jar;lib\log4j-core-2.22.1.jar;lib\log4j-slf4j2-impl-2.22.1.jar;lib\slf4j-api-2.0.9.jar
-Xms96m
-Xmx96m
-XX:+UseSerialGC
-XX:TieredStopAtLevel=1
-XX:ReservedCodeCacheSize=48m
-XX:MaxDirectMemorySize=128m
